/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

//-----------------------------
//Includes
//-----------------------------
#include "STM32F103x6.h"
#include "STM32F103C6_GPIO_driver.h"

void Clock_Init(void)
{
	// IO port A clock enable
	RCC_GPIOA_CLK_EN();
	// IO port B clock enable
	RCC_GPIOB_CLK_EN();
}

void GPIO_Init(void)
{
	GPIO_PinConfig_t *PinCfg = NULL;


	// Pin1 Port A: 00 Floating Input mode (reset state)
	PinCfg->GPIO_PinNumber = GPIO_PIN_1;
	PinCfg->GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, PinCfg);

	// Pin13 Port A: 01 Floating input (reset state)
	PinCfg->GPIO_PinNumber = GPIO_PIN_13;
	PinCfg->GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, PinCfg);

	// Pin1 Port B: 00 General purpose output push-pull
	// Pin1 Port B: 01 Output mode, max speed 10 MHz.
	PinCfg->GPIO_PinNumber = GPIO_PIN_1;
	PinCfg->GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg->GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, PinCfg);
	//Turn OFF led on Pin1 PortB
	MCAL_GPIO_WritePin(GPIOB, GPIO_PIN_1, GPIO_PIN_SET);

	// Pin13 Port B: 00 General purpose output push-pull
	// Pin13 Port B: 01 Output mode, max speed 10 MHz.
	PinCfg->GPIO_PinNumber = GPIO_PIN_13;
	PinCfg->GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg->GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, PinCfg);
	//Turn OFF led on Pin13 PortB
	MCAL_GPIO_WritePin(GPIOB, GPIO_PIN_13, GPIO_PIN_SET);
}

void delay_ms(uint8_t x)
{
	uint8_t i,j;
	for(i = 0; i < x; i++)
		for(j = 0; j < 255; j++);
}

int main(void)
{
	Clock_Init();
	GPIO_Init();

	while(1)
	{
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == GPIO_PIN_RESET) // single press
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == GPIO_PIN_RESET);
		}

		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == GPIO_PIN_SET) // multi pressing
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
			delay_ms(2);
		}
	}

	return 0;
}

