/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

//-----------------------------
//Includes
//-----------------------------
#include "core_cm3.h"

void PendSV_Handler()
{
	// Clear PendSv
	SCB->ICSR |= SCB_ICSR_PENDSVCLR_Msk;
}

void OS_SVC(uint32_t* Stack_Frame)
{
	// R0 is a pointer to OS_SVC_Set stack frame
	// R0, R1, R2, R3, R12, LR, Return Address (PC), xPSR
	uint8_t SVC_Number;
	uint32_t val1, val2;

	val1 = Stack_Frame[0];
	val2 = Stack_Frame[1];
	SVC_Number = *((uint8_t*)(((uint8_t*)Stack_Frame[6]) - 2));

	switch(SVC_Number)
	{
		case 1: // OS ADD
			Stack_Frame[0] = val1 + val2;
			break;
		case 2: // OS SUB
			Stack_Frame[0] = val1 - val2;
			break;
		case 3: // OS MUL
			Stack_Frame[0] = val1 * val2;
			break;
		case 4: // OS PendSV
			// Set PendSv
			SCB->ICSR |= SCB_ICSR_PENDSVSET_Msk;
			break;
	}
}

__attribute__ ((naked)) void SVC_Handler()
{
	__asm volatile ("TST LR,#0x04 \n\t"
					"ITE EQ \n\t"
					"MRSEQ R0,MSP \n\t"
					"MRSNE R0,PSP \n\t"
					"B OS_SVC");
}

uint32_t OS_SVC_Set(uint32_t a, uint32_t b, uint32_t SVC_ID)
{
	uint32_t ret_val = 0;
	switch(SVC_ID)
	{
		case 1: // OS ADD
			__asm volatile ("SVC #0x01");
			break;
		case 2: // OS SUB
			__asm volatile ("SVC #0x02");
			break;
		case 3: // OS MUL
			__asm volatile ("SVC #0x03");
			break;
		case 4: // OS PendSV
			__asm volatile ("SVC #0x04");
			break;
	}

	__asm volatile ("MOV %0,R0" : "=r" (ret_val));
	return ret_val;
}

int main(void)
{
	uint32_t result = 0;

	result = OS_SVC_Set(3,2,1); // Add
	result = OS_SVC_Set(3,2,2); // Sub
	result = OS_SVC_Set(3,2,3); // Mul
	result = OS_SVC_Set(0,0,4); // PendSV

	while(1)
	{

	}

	return 0;
}

