/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include<stdint.h>

// RCC
#define RCC_BASE     0x40021000
#define RCC_APB2ENR  *((volatile uint32_t*)(RCC_BASE   + 0x18))

// GPIO PortA
#define GPIOA_BASE   0x40010800
#define GPIOA_CRL    *((volatile uint32_t*)(GPIOA_BASE + 0x00))
#define GPIOA_CRH    *((volatile uint32_t*)(GPIOA_BASE + 0x04))
#define GPIOA_IDR    *((volatile uint32_t*)(GPIOA_BASE + 0x08))
#define GPIOA_ODR    *((volatile uint32_t*)(GPIOA_BASE + 0x0C))

// GPIO PortB
#define GPIOB_BASE   0x40010C00
#define GPIOB_CRL    *((volatile uint32_t*)(GPIOB_BASE + 0x00))
#define GPIOB_CRH    *((volatile uint32_t*)(GPIOB_BASE + 0x04))
#define GPIOB_IDR    *((volatile uint32_t*)(GPIOB_BASE + 0x08))
#define GPIOB_ODR    *((volatile uint32_t*)(GPIOB_BASE + 0x0C))

void Clock_Init(void)
{
	// IO port A clock enable
	RCC_APB2ENR |= (1<<2);

	// IO port B clock enable
	RCC_APB2ENR |= (1<<3);
}

void GPIO_Init(void)
{
	// Pin11 Port A: 00 Input mode (reset state)
	GPIOA_CRL &= ~(0b11<<4);
	// Pin1 Port A: 01 Floating input (reset state)
	GPIOA_CRL &= ~(0b11<<6);
	GPIOA_CRL |= (0b01<<6);

	// Pin13 Port A: 00 Input mode (reset state)
	GPIOA_CRH &= ~(0b11<<20);
	// Pin13 Port A: 01 Floating input (reset state)
	GPIOA_CRH &= ~(0b11<<22);
	GPIOA_CRH |= (0b01<<22);

	// Pin1 Port B: 01 Output mode, max speed 10 MHz.
	GPIOB_CRL &= ~(0b11<<4);
	GPIOB_CRL |= (0b01<<4);
	// Pin1 Port B: 00 General purpose output push-pull
	GPIOB_CRL &= ~(0b11<<6);
	// write 5v on pin1 PortB
	GPIOB_ODR |= (1<<1);

	// Pin13 Port B: 01 Output mode, max speed 10 MHz.
	GPIOB_CRH &= ~(0b11<<20);
	GPIOB_CRH |= (0b01<<20);
	// Pin13 Port B: 00 General purpose output push-pull
	GPIOB_CRH &= ~(0b11<<22);
	// write 5v on pin13 PortB
	GPIOB_ODR |= (1<<13);
}

void delay_ms(uint8_t x)
{
	uint8_t i,j;
	for(i = 0; i < x; i++)
		for(j = 0; j < 255; j++);
}

int main(void)
{
	Clock_Init();
	GPIO_Init();

	while(1)
	{
		if((( GPIOA_IDR & (1<<1))>>1 ) == 0) // single press
		{
			GPIOB_ODR ^= (1<<1);
			while((GPIOA_IDR & (1<<1))>>1 == 0);
		}

		if((( GPIOA_IDR & (1<<13))>>13 ) == 1) // multi pressing
		{
			GPIOB_ODR ^= (1<<13);
			delay_ms(2);
		}
	}

	return 0;
}
