/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "STM32F103x6.h"
#include "I2C_Slave_EEPROM.h"

void Clock_Init(void)
{
	// IO port B clock enable
	RCC_GPIOB_CLK_EN();
	// AFIO clock enable
	RCC_AFIO_CLK_EN();
}

int main(void)
{
	Clock_Init();
	EEPROM_Init();

	//Test Case 1
	uint8_t ch1[] = {0x01,0x02,0x03,0x04,0x05,0x06,0x07};
	uint8_t ch2[7] = {0};
	EEPROM_Write_NBytes(0xAF, ch1, 7);
	EEPROM_Read_NBytes(0xAF, ch2, 7);

	//Test Case 2
	ch1[0] = 0xA;
	ch1[1] = 0xB;
	ch1[2] = 0xC;
	ch1[3] = 0xD;
	EEPROM_Write_NBytes(0xFFF, ch1, 4);
	EEPROM_Read_NBytes(0xFFF, ch2, 4);

	while(1);
	return 0;
}
