/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

//-----------------------------
//Includes
//-----------------------------
#include "Scheduler.h"

Task_Ref Task1, Task2, Task3;
volatile static uint8_t task1_flag, task2_flag, task3_flag;

void task1()
{
	while(1)
	{
		// Task1 code
		task1_flag ^= 1;
	}
}

void task2()
{
	while(1)
	{
		// Task2 code
		task2_flag ^= 2;
	}
}

void task3()
{
	while(1)
	{
		// Task3 code
		task3_flag ^= 3;
	}
}

int main(void)
{
	MyRTOS_errorID error_status = NoError;
	// Hardware_Init (Initialize Clock Tree , RestController)
	HW_Init();

	error_status = MyARTOS_Init();
	if(error_status != NoError)
		while(1);

	strcpy((char*)Task1.TaskName, "Task1");
	Task1.Stack_Size = 512;
	Task1.p_TaskEntry = task1;
	Task1.Priority = 3;

	strcpy((char*)Task2.TaskName, "Task2");
	Task2.Stack_Size = 512;
	Task2.p_TaskEntry = task2;
	Task2.Priority = 3;

	strcpy((char*)Task3.TaskName, "Task3");
	Task3.Stack_Size = 512;
	Task3.p_TaskEntry = task3;
	Task3.Priority = 3;

	error_status = MyRTOS_CreateTask(&Task1);
	error_status = MyRTOS_CreateTask(&Task2);
	error_status = MyRTOS_CreateTask(&Task3);

	error_status = MyRTOS_ActivateTask(&Task1);
	error_status = MyRTOS_ActivateTask(&Task2);
	error_status = MyRTOS_ActivateTask(&Task3);

	MyRTOS_StartOS();

	while(1);

	return 0;
}

