/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

//-----------------------------
//Includes
//-----------------------------
#include "STM32F103x6.h"
#include "STM32F103C6_GPIO_driver.h"
#include "STM32F103C6_EXTI_driver.h"
#include "LCD.h"

uint8_t IRQ_flag;

void Clock_Init(void)
{
	// IO port A clock enable
	RCC_GPIOA_CLK_EN();
	// IO port B clock enable
	RCC_GPIOB_CLK_EN();
	// AFIO clock enable
	RCC_AFIO_CLK_EN();
}

static void delay_ms(uint8_t time_ms)
{
	uint8_t i,j;
	for(i = 0; i < time_ms; i++)
		for(j = 0; j < 255; j++);
}

void EXTI9_CallBack(void)
{
	IRQ_flag = 1;
	LCD_Write_String((uint8_t*)"IRQ EXTI9 happened -|_");
	delay_ms(255);
}

int main(void)
{
	Clock_Init();
	LCD_Init();

	EXTI_PinConfig_t EXTI_Config;
	// EXTI9 PortB Pin9, Falling edge trigger
	EXTI_Config.EXTI_Pin = EXTI9PB9;
	EXTI_Config.Trigger_Case = EXTI_TRIGGER_FALLING;
	EXTI_Config.P_IRQ_CallBack = EXTI9_CallBack;
	EXTI_Config.IRQ_EN = EXTI_IRQ_ENABLE;

	MCAL_EXTI_GPIO_Init(&EXTI_Config);
	IRQ_flag = 1;

	while(1)
	{
		if(IRQ_flag)
		{
			LCD_Clear_Screen();
			IRQ_flag = 0;
		}
	}

	return 0;
}

